import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import { DarkmodContext } from "./context/darkmodecontext";
import Email from "./email";
import Navbar from "./navbar";
import Sidebar from "./sidebar";

function Layout() {
    const {darkmodOn  , setDarkmod} =  useContext(DarkmodContext)
    const [loaing , setloading] = useState(true);
    useEffect(()=>{
      setloading(true)
      setTimeout(() => {
        setloading(false)
      }, 200);
    },[])

    const them = (lightmod, darkmod) => {
        if (darkmodOn) return darkmod;
        else return lightmod;
      };
    return (  <>
    <Head>
        <title>my work</title>
        <meta name="description" content="Generated by create next app" />
    </Head>
      
     
   <Navbar them={them} setDarkmod= {setDarkmod} />
   <Email />
        <Sidebar them={them} setDarkmod={setDarkmod} />
   </>
     );
}

export default Layout;