import Image from "next/image";

import { useContext, useEffect, useRef, useState } from "react";
import { BsArrowDown } from "react-icons/bs";
import Navbar from "./navbar";
import Sidebar from "./sidebar";
import Email from "./email";
import { FiExternalLink } from "react-icons/fi";
import { DarkmodContext } from "./context/darkmodecontext";
import LoadingItem from "./loadingitem";
import Layout from "./layout";

/* 
 <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
 </Head>
*/

export default function Root({ period }) {
  const [loaing, setloading] = useState(true);
  useEffect(() => {
    setloading(true)
    setTimeout(() => {
      setloading(false)
    }, period);
  }, [])

  const { darkmodOn, setDarkmod } = useContext(DarkmodContext)
  const fremworks = [
    {
      name: "React.js",
      url: "",
      imgUrl: "https://cdn-icons-png.flaticon.com/512/1126/1126012.png",
    },
    {
      name: "next.js",
      url: "",
      imgUrl: "https://osakalehusky.com/uploads/162b322667158e911325_1655906918.png",
    },
    {
      name: "noode.js",
      url: "",
      imgUrl: "https://innovationyourself.com/wp-content/uploads/2020/08/nodejs-logo.png",
    },
    {
      name: "mongoose",
      url: "",
      imgUrl: "https://miro.medium.com/max/1050/1*acfAKaDI7uv5GyFnJmiPhA.png",
    },
    {
      name: "AndroidStudio",
      url: "",
      imgUrl: "https://cdn.icon-icons.com/icons2/3053/PNG/512/android_studio_alt_macos_bigsur_icon_190395.png",
    },
    // https://cdn.icon-icons.com/icons2/3053/PNG/512/android_studio_alt_macos_bigsur_icon_190395.png

    // https://miro.medium.com/max/1050/1*acfAKaDI7uv5GyFnJmiPhA.png
  ]
  const languages = [
    {
      name: "c/c++",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/74/74897.png",
    },
    {
      name: "java / android",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/226/226777.png",
    },
    {

      name: "javascript",
      url: "",
      imgUrl:
        "https://www.freepnglogos.com/uploads/javascript-png/png-javascript-badge-picture-8.png",
    },
    {
      name: "html",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/63/63767.png",
    },
    {
      name: "css",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/919/919826.png",
    },


    {
      name: "linux/bash",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/25/25719.png",
    },
    {
      name: "PhP",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/919/919830.png",
    },
    {
      name: "SQL",
      url: "",
      imgUrl:
        "https://cdn-icons-png.flaticon.com/512/5815/5815809.png",
    },
    {
      name: "Mongodb",
      url: "",
      imgUrl:
        "https://community-cdn-digitalocean-com.global.ssl.fastly.net/Mu3tf3evRUuYT2mbdPd93vmC",
    },

  ];
  const text = [
    " I got my bacaloria degree in  physics option . in this period i was interested about maths and physics and from "+
    "time to time i play some vedio games , for that reasen i was always asking my self how do they works but i wasn't that match interested   ",

    "2022 I took the most important step in my life , i passed the ENSA concour and i get my place on it , then my life start "+
    "to create it self , the first your at ensa we studied some programming languages like c , matlab and mapple i'feel really confortable when i "+
    "code with them especialy c so i started to love this domain .",

    " 2021 also was a very important part in my formation because i chosed the software engeenering as a main domain  , after "+
    "discovering that it's the only domain that i can spend a lot of time doing it without feeling tired . ",

    " 2022 i'm beeing love with mern stack web develppment , to improve my skills i create meny web apps you can find them on "+
    "my work page ,  ",
  ];
  const [placeholder, setPlaceholder] = useState("");
  const [progresspoint, setprogresspoint] = useState(0);
  const string = " .<div/>.",
    index = useRef(0);

  useEffect(() => {
    function tick() {
      setPlaceholder((prev) => prev + string[index.current]);
      index.current++;
    }
    function free() {
      setPlaceholder(".");
      index.current = 0;
    }
    if (index.current < string.length - 1) {
      let addChar = setInterval(tick, 250);
      return () => clearInterval(addChar);
    } else {
      let addChar = setInterval(free, 500);
      return () => clearInterval(addChar);
    }
  }, [placeholder]);


  const them = (lightmod, darkmod) => {
    if (darkmodOn) return darkmod;
    else return lightmod;
  };
  return (
    // verydark #06064d  light #7ae2e4
    // not that dark #3603bd
    <div
      className={
        them(" text-gray-500 bg-gray-100", "bg-darkmod  text-white") +
        " themchange"
      }
    >

      {loaing ? <div className=" w-full h-screen overflow-hidden"><LoadingItem /></div> :
        <main className=" m-auto container min-h-screen ">
          <Layout />
          <section className={"pt-20 lg:mx-20 mx-4 min-h-screen  "}>
            <h4 className=" font-mono mt-20 text-gray-400">
              {" "}
              Hi world , my name is{" "}
            </h4>
            <h1 className="  text-6xl  font-bold my-4">
              Hamza Douaij{" "}
              <span className="font-mono opacity-50 block lg:inline">
                {placeholder}
              </span>
            </h1>
            <p
              className={
                "font-mono text-xl lg:w-7/12 w-9/12 " +
                them("text-gray-700", "text-blugreen")
              }
            >
              {" "}
              I’m a software engineer specializing in building (and occasionally
              designing) exceptional digital experiences. Currently, I’m focused
              on building MERN STACK Web applications using{" "}
              <a href="https://reactjs.org/" className="text-blue-600">
                React.js
              </a>{" "}
              ,{" "}
              <a href="https://nextjs.org/" className="text-blue-600">
                {" "}
                Next.js{" "}
              </a>
              express.js and mongodb
            </p>
            <div className=" flex lg:justify-end justify-center  overflow-visible mt-20 md:mt-0">
              <div className="img-container  bg-blugreen  relative w-300 md:h-300">
                <p
                  className={
                    "font-mono p-3 " + them("text-white", "text-gray-600")
                  }
                >
                  "I’m 21 years old software engeeniering student . I am always
                  looking to develop my skills . I really enjoyed the hard work in
                  everything related with the sofwares , which helped me to
                  construct my self from different points of view. I love to learn
                  new things nd i'm so motivated to make it happen .
                </p>
                <div className="imgwrapper  md:absolute md:top-0 md:right-0 md:left-0 md:buttom-0} ">
                  <Image
                    src={"/image.jpg"}
                    width={300}
                    height={300}
                    className=" object-cover"
                  />
                </div>
              </div>
            </div>
            <div className="md:flex justify-center hidden mt-4">
              <a href="#about">
                <div
                  className={
                    " animate-bounce rounded-fullp-3 font-bold p-3 rounded-full shadow-lg " +
                    them(
                      " text-white shadow-blue-300 bg-black",
                      "shadow-gray-500  bg-blue-800 "
                    )
                  }
                >
                  {<BsArrowDown />}
                </div>
              </a>
            </div>{" "}
          </section>
          <section
            className={
              "pt-20 lg:mx-20  min-h-screen flex justify-center items-center"
            }
            id={"about"}
          >
            <div
              className={
                "flex md:w-8/12 w-11/12 rounded border-2 p-2 border-blue-200  " +
                them(" bg-blue-100", "border-blue-700")
              }
            >
              <div className=" md:flex-1 flex items-center font-mono ">
                <ul className=" md:py-20">
                  <li
                    className=" md:pr-3   hover:bg-hoverdark rounded cursor-pointer  "
                    onClick={() => {
                      setprogresspoint(0);
                    }}
                  >
                    <div className="flex ">
                      <div className="w-10 flex justify-center relative">
                        <div className=" absolute  h-full w-full flex justify-center items-center">
                          {progresspoint === 0 && (
                            <div className=" h-4 w-4 rounded-full bg-blue-700 shadow-lg  shadow-gray-400 ">
                              {" "}
                            </div>
                          )}
                        </div>
                        <div className="bg-blue-500 h-full w-0.5 flex justify-center items-center overflow-visible"></div>
                      </div>
                      <div className="p-4">2019 </div>
                    </div>
                  </li>
                  <li
                    className=" md:pr-3   hover:bg-hoverdark rounded cursor-pointer  "
                    onClick={() => {
                      setprogresspoint(1);
                    }}
                  >
                    <div className="flex ">
                      <div className="w-10 flex justify-center relative">
                        <div className=" absolute  h-full w-full flex justify-center items-center">
                          {progresspoint === 1 && (
                            <div className=" h-4 w-4 rounded-full bg-blue-700 shadow-lg  shadow-gray-400 ">
                              {" "}
                            </div>
                          )}
                        </div>
                        <div className="bg-blue-500 h-full w-0.5 flex justify-center items-center overflow-visible"></div>
                      </div>
                      <div className="p-4">2020 </div>
                    </div>
                  </li>
                  <li
                    className=" md:pr-3   hover:bg-hoverdark rounded cursor-pointer  "
                    onClick={() => {
                      setprogresspoint(2);
                    }}
                  >
                    <div className="flex ">
                      <div className="w-10 flex justify-center relative">
                        <div className=" absolute  h-full w-full flex justify-center items-center">
                          {progresspoint === 2 && (
                            <div className=" h-4 w-4 rounded-full bg-blue-700 shadow-lg  shadow-gray-400 ">
                              {" "}
                            </div>
                          )}
                        </div>
                        <div className="bg-blue-500 h-full w-0.5 flex justify-center items-center overflow-visible"></div>
                      </div>
                      <div className="p-4">2021 </div>
                    </div>
                  </li>
                  <li
                    className=" md:pr-3  hover:bg-hoverdark rounded cursor-pointer  "
                    onClick={() => {
                      setprogresspoint(3);
                    }}
                  >
                    <div className="flex ">
                      <div className="w-10 flex justify-center relative">
                        <div className=" absolute  h-full w-full flex justify-center items-center">
                          {progresspoint === 3 && (
                            <div className=" h-4 w-4 rounded-full bg-blue-700 shadow-lg  shadow-gray-400 ">
                              {" "}
                            </div>
                          )}
                        </div>
                        <div className="bg-blue-500 h-full w-0.5 flex justify-center items-center overflow-visible"></div>
                      </div>
                      <div className="p-4">2022 </div>
                    </div>
                  </li>
                </ul>
                <div className="flex-1 p-3  ">{text[progresspoint]}</div>
              </div>
              <div className="  flex-1 relative hidden lg:block rounded-md overflow-hidden">
                <Image
                  src={"/backgound.jpg"}
                  layout="fill"
                  className=" h-full w-full object-cover"
                />
              </div>
            </div>
          </section>
          <section className={"pt-20 lg:mx-20 mx-4 min-h-screen  "}>
            <div className="">
              <h1 className=" text-5xl text-center mb-10">languages i learned</h1>
              <div className="m-1 p-1 gap-4 grid xl:grid-cols-6 lg:grid-cols-4 sm:grid-cols-3 grid-cols-2 ">
                {languages.map((fremwork) =>
                  <div className={"rounded border-blue-500  border-2 p-3 hover:scale-101 hover:shadow-lg " + them('bg-blue-100', ' bg-hoverdark hover:bg-hoverlight')} key={fremwork.name}>
                    <div className="  rounded-md relative xl:h-40 h-32 col-span-1   ">
                      <img
                        src={
                          fremwork.imgUrl
                        }
                        className=" h-full w-full object-contain "
                      />
                    </div>
                    <div className="flex items-center justify-center p-2 text-xl gap-2">
                      <span> {fremwork.name}</span>
                      <a className="text-blue-200" href={fremwork.url}>
                        {<FiExternalLink />}
                      </a>
                    </div>
                  </div>
                )}
              </div>
            </div>

          </section>
          <section className={"pt-20 lg:mx-20 mx-4 min-h-screen  "}>
            <div className="">
              <h1 className=" text-5xl text-center mb-10">fremworks i work with</h1>
              <div className="m-1 p-1 gap-4 grid xl:grid-cols-6 lg:grid-cols-4 sm:grid-cols-3 grid-cols-2 justify-center ">
                {fremworks.map((fremwork) =>
                  <div className={"rounded border-blue-500  border-2 p-3 hover:scale-101 hover:shadow-lg " + them('bg-blue-100', ' bg-hoverdark hover:bg-hoverlight')} key={fremwork.name}>
                    <div className="  rounded-md relative xl:h-40 h-32 col-span-1   ">
                      <img
                        src={
                          fremwork.imgUrl
                        }
                        className=" h-full w-full object-contain "
                      />
                    </div>
                    <div className="flex items-center justify-center p-2 text-xl gap-2">
                      <span> {fremwork.name}</span>
                      <a className="text-blue-200" href={fremwork.url}>
                        {<FiExternalLink />}
                      </a>
                    </div>
                  </div>
                )}
              </div>
            </div>

          </section>
        </main>}
    </div>
  );
}
