import Home from "./home";
import Root from "../components/root";
import Head from "next/head";

/* 
 <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
 </Head>
*/

export default function home() { 
  
  return (
    <>  <Head>
    <title>Hamza_douaij</title>
    <meta name="description" content="Generated by create next app" />
  </Head>
  <Root period={100}/>
   </>
 );
}
